### PR TITLE
Add meal_plan sensor

### LINKED ISSUE #45: Feature Request: Meal Plan entries with Recipe/Product names
Ability to view the Meal Plan entries in a Calendar like way would be a great addition to this sensor. 

https://github.com/grocy/grocy/issues/777

### PR DESCRIPTION
**Pull request by nervetattoo**
This adds the `sensor.grocy_meal_plan` sensor. Attributes looks like this (for the demo data in grocy):

Fixes #45 

```yaml
items: 
- day: '2020-08-10T00:00:00+00:00'
  note: null
  recipe_name: Pizza
  desired_servings: 1
  picture_url: >-
    http://localhost:8085/api/files/recipepictures/cGl6emEuanBn?force_serve_as=picture&best_fit_width=400
- day: '2020-08-11T00:00:00+00:00'
  note: null
  recipe_name: Spaghetti bolognese
  desired_servings: 1
  picture_url: >-
    http://localhost:8085/api/files/recipepictures/c3BhZ2hldHRpLmpwZw==?force_serve_as=picture&best_fit_width=400
...
```

### CODE REVIEW

**Comment by nervetattoo** [comment]
I've tried to keep the number of fields on each item low to avoid huge raw dumps of data like the other sensors has. Its relatively easy to add more fields by adding them to the MealPlanItem class.

**Comment by isabellaalstrom** [comment]
Are you supposed to be able to open the picture url in the browser? Because I can't

**Comment by nervetattoo** [comment]
> Are you supposed to be able to open the picture url in the browser? Because I can't

Well, yes 😛 That URL needs a port map to be set up for the hassio addon. I'll test it more and continue working on this functionality. I'm planning a meal plan card but not had time to start on it, that'll reveal better if the fields are sufficient and work well enough. Probably more coming there next week.

**Comment by isabellaalstrom** [comment]
Oh that's great! I was planning on making a card for that too, but then I'll hold off :)

**Comment by isabellaalstrom** [comment]
I have made this card now, so that it's visible that this is going to be happening :) https://github.com/custom-components/grocy/projects/1#card-43733907

**Comment by isabellaalstrom** [comment]
I do have a port map though, and still can't see the picture.

**Comment by nervetattoo** [comment]
Seems like the image part is due to the images requiring auth. Its possible to send the api key as part of the query string, but that would expose the key which is not ideal. I'll have to add a http endpoint in the component that proxies with tokens to the underlying grocy instance. Can make it generic to support all picture types (products, recipes, ...)

**Pull request merged**
