### PR TITLE
Create hr.json for Croatian Translation

### PR DESCRIPTION
**Pull request by BeardedTinker**
Translation to Croatian language

### CODE REVIEW

**Comment by isabellaalstrom** [comment]
Thank you for your contribution, however I just recently moved the translations to work with Lokalise. Please [join](https://app.lokalise.com/public/260939135f7593a05f2b79.75475372/) and contribute your translations there!

**Comment by BeardedTinker** [comment]
Will do! Thanks!

**Comment by BeardedTinker** [comment]
I tried to do it in lokalise but I see and can edit only English.

**Comment by ludeeus** [comment]
Languages need to be manually added by an admin, Croatian is added now.

**Pull request closed without merging**
