### PR TITLE
Upgrade pygrocy to 1.5.0

### LINKED ISSUE #241: API call error when tracking a chore
When tracking a chore using the home assistant Chores view an error occurs when calling the web api.
Home Assistant version is 2022.7.7 (2022.8.1 also), Grocy component 3.2, Grocy card 4.4.

Full error log:
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/grocy/services.py:171
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 10:32:34 AM (5 occurrences)
Last logged: 10:43:37 AM

[140237094295664] 'datetime.timezone' object has no attribute 'localize'
[140236378552208] 'datetime.timezone' object has no attribute 'localize'
[140236911339856] 'datetime.timezone' object has no attribute 'localize'
[140236351267088] 'datetime.timezone' object has no attribute 'localize'
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 193, in handle_call_service
await hass.services.async_call(
File "/usr/src/homeassistant/homeassistant/core.py", line 1713, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1750, in _execute_service
await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
File "/config/custom_components/grocy/services.py", line 107, in async_call_grocy_service
await async_execute_chore_service(hass, coordinator, service_data)
File "/config/custom_components/grocy/services.py", line 173, in async_execute_chore_service
await hass.async_add_executor_job(wrapper)
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/grocy/services.py", line 171, in wrapper
coordinator.grocy_api.execute_chore(chore_id, done_by)
File "/usr/local/lib/python3.10/site-packages/pygrocy/grocy.py", line 127, in execute_chore
return self._api_client.execute_chore(chore_id, done_by, tracked_time)
File "/usr/local/lib/python3.10/site-packages/pygrocy/grocy_api_client.py", line 398, in execute_chore
localized_tracked_time = localize_datetime(tracked_time)
File "/usr/local/lib/python3.10/site-packages/pygrocy/utils.py", line 47, in localize_datetime
return local_tz.localize(timestamp).astimezone(pytz.utc)
AttributeError: 'datetime.timezone' object has no attribute 'localize'

### LINKED ISSUE #251: Can you update pygrocy requirement to 1.5.0 ? There is an issue with pydantic version requirement which was solved in pygrocy 1.5.0
Hello,

currently when I try to install Grocy component I'm getting error:

```
Logger: homeassistant.util.package
Source: util/package.py:98
First occurred: 12:22:02 (3 occurrences)
Last logged: 12:22:14

Unable to install package pygrocy==1.4.1: ERROR: Will not install to the user site because it will lack sys.path precedence to pydantic in /snap/home-assistant-snap/527/lib/python3.10/site-packages
```

this is related to pygrocy 1.4.1 require older version od pydantic which is already installed. This has been resolved here:

https://github.com/SebRut/pygrocy/commit/6d5dae76efbcf0abe06baafaaf4461bcb66db541#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7

in pygrocy 1.5.0 release.

Thanks

### PR DESCRIPTION
**Pull request by marcelvriend**
Upgrade pygrocy to 1.5.0.

Fixes #241, Fixes #251

### CODE REVIEW

**Review by excalbian — APPROVED** [review]
I made this change locally and everything still worked as expected (using v4.7.1 of the custom component).

**Comment by MrOwen** [comment]
Is the pygrocy upgrade still needed? I tried setting up the custom card component with no luck and wondering if it was due to the version still being at `1.4.1`. I saw your forked repo was removed so wasn't sure if this was still planned.

**Comment by isabellaalstrom** [comment]
@marcelvriend Should this be done? I see that it's only closed after you deleted the head repo

**Comment by Johan1990** [comment]
Relating to #241, this one is not yet fixed. Altough, I'm running Grocy in a docker container on version 3.3.2. Far as I can see that is the latest version of that docker. Will that also be updated when 1.5.0 is available?

**Pull request closed without merging**
