### PR TITLE
update README

### PR DESCRIPTION
**Pull request by BlueBlueBlob**
#33

### CODE REVIEW

**Comment by SebRut** [comment]
I guess we should still include the manual steps

**Comment by BlueBlueBlob** [comment]
For hassio user ?

**Comment by SebRut** [comment]
More like generally_
1. ui based instructions with HACS
2. additional info for HASSio
3. manual setup by using configuration.yaml

**Comment by BlueBlueBlob** [comment]
3. is not needed anymore since config flow
README in HACS changes regarding version (or maybe I'm wrong) so config.yaml will be here for older version. I need to check this.

**Comment by SebRut** [comment]
Not needed but some users might prefer to manually configurate their integrations.

**Comment by BlueBlueBlob** [comment]
With 
```
async def async_setup(hass, config):
    """Set up this component."""
    return True
```
It's not possible anymore.

**Comment by SebRut** [comment]
Alright, seems good for now. WE might have to make this possible again in the future if there is sufficient demand.

**Pull request merged**
