### PR TITLE
item.day is already a date

### LINKED ISSUE #171: [BUG] Update of Meal_plan failed with 'datetime.date' object has no attribute 'date'
## Unless all relevant information is provided, I can't help you

**Describe the bug**
Meal plans are no longer working.

**Expected behavior**
Meal plans to populate.

**To Reproduce**
1. Start Home Assistant

### General information to help debugging:
**What sensors do you have enabled? Are they working and/or what state are they in? Do you have the corresponding functions enabled in Grocy?**

**What is your installed versions of Home Assistant, Grocy and this integration?**

HA version core-2021.12.10
Grocy Integration version 4.1.0

**How do you have Grocy installed? Add-on or external?**
Docker container version 3.1.3

**Have you added debugging to the log, and what does the log say?**
```
2022-01-25 12:04:20 ERROR (MainThread) [custom_components.grocy] Update of Meal_plan failed with 'datetime.date' object has no attribute 'date'
2022-01-25 12:04:20 DEBUG (MainThread) [custom_components.grocy] Finished fetching grocy data in 112.654 seconds (success: True)
2022-01-25 12:04:20 DEBUG (MainThread) [custom_components.grocy.sensor] Data for sensor.grocy_chores: None
2022-01-25 12:04:20 DEBUG (MainThread) [custom_components.grocy.sensor] Data for sensor.grocy_meal_plan: None
2022-01-25 12:04:20 DEBUG (MainThread) [custom_components.grocy.sensor] Data for sensor.grocy_tasks: []
```

**JSON service data (if related to using a service)**
```json
{

}
```

**Additional context**
`Update of Meal_plan failed with 'datetime.date' object has no attribute 'date'`

### PR DESCRIPTION
**Pull request by ludeeus**
<https://github.com/SebRut/pygrocy/blob/v1.0.0/pygrocy/data_models/meal_items.py#L103>
<https://github.com/SebRut/pygrocy/blob/v1.0.0/pygrocy/grocy_api_client.py#L36>

Fixes #171

### CODE REVIEW

**Comment by firstof9** [comment]
Thanks! I just started digging into this, you beat me to the punch. :beers:

**Comment by firstof9** [comment]
Just tested this looks like another error has popped up.

```
2022-01-25 14:49:14 ERROR (MainThread) [custom_components.grocy] Update of Chores failed with 1 validation error for CurrentChoreResponse
next_estimated_execution_time
  none is not an allowed value (type=type_error.none.not_allowed)

2022-01-25 14:50:54 ERROR (MainThread) [custom_components.grocy] Update of Meal_plan failed with 1 validation error for MealPlanSectionResponse
sort_number
  value is not a valid integer (type=type_error.integer)
```

Not sure about the Chores one.

**Comment by firstof9** [comment]
The sensor doesn't populate here's the debug output:

```
2022-01-25 15:14:11 DEBUG (MainThread) [custom_components.grocy] Finished fetching grocy data in 111.195 seconds (success: True)
2022-01-25 15:14:11 DEBUG (MainThread) [custom_components.grocy.sensor] Data for sensor.grocy_meal_plan: [<custom_components.grocy.helpers.MealPlanItem object at 0x7ff83e182e20>, <custom_components.grocy.helpers.MealPlanItem object at 0x7ff8415abca0>, <custom_components.grocy.helpers.MealPlanItem object at 0x7ff84573f250>, <custom_components.grocy.helpers.MealPlanItem object at 0x7ff8411d8550>, <custom_components.grocy.helpers.MealPlanItem object at 0x7ff84a343dc0>]
```

**Comment by ludeeus** [comment]
That's unrelated to this change, lastest beta release contains a similar fix, if you don't figure it out open an issue for it

**Comment by ludeeus** [comment]
<https://github.com/custom-components/grocy/pull/175> will not fix your issue, but will help identifying it

**Pull request merged**
