### PR TITLE
WIP: basic config flow integration

### PR DESCRIPTION
**Pull request by SebRut**

### CODE REVIEW

**Comment by BlueBlueBlob** [comment]
Hey :)

I'm doing a custom component too. My config flow is working (not so easy ;) )

But what do you want to do ? Because config flow is useful when user interaction is needed (like two auth steps).

If it's just for fancy feature to be in HA integration menu : it's really easy :)

**Comment by SebRut** [comment]
Yeah just that fancy integration menu thing to input URL and API key :D

**Comment by BlueBlueBlob** [comment]
Sorry

**Comment by BlueBlueBlob** [comment]
Btw : https://community.home-assistant.io/t/custom-component-google-tasks-wip/141985

Don't know what to say, you are my python master :)

I have to try some stuff on show_form function like :
Can we have switch or check box (just for fancy :) )

**Comment by SebRut** [comment]
Closed as done in #22

**Pull request closed without merging**
